export { default as Register } from "./pages/Register"
export { default as Login } from "./pages/Login"
export { default as ForgotPassword } from "./pages/ForgotPassword"
export { default as Layout } from "../layout"
export { default as Dashboard } from "./pages/Dashboard"
export { default as AddProduct } from "./pages/AddProduct"
