import { RiFacebookCircleLine, RiInstagramLine, RiTwitchLine, RiHome4Line, RiYoutubeLine, RiBarChart2Line, RiMailSendLine, RiDiscountPercentLine, RiTruckLine, RiBankCardLine, RiLockLine, RiReplay10Line, RiArrowRightLine, RiArrowLeftLine, RiSearchLine, RiShoppingCart2Line, RiCheckboxCircleFill, RiCheckboxCircleLine, RiCloseLine, RiAddLine, RiSubtractLine, RiCloseCircleFill, RiDeleteBinLine, RiEdit2Line, RiArrowRightDoubleLine, RiCloseCircleLine, RiStore2Line, RiMapPin2Line, RiMoneyRupeeCircleLine, RiPieChartLine, RiAddCircleLine, RiListCheck3, RiCalendarCheckLine, RiMenu2Line, RiHistoryLine, RiSettingsLine, RiUserLine, RiLogoutCircleRLine, RiUpload2Line } from "@remixicon/react"

const icons = {
  home: RiHome4Line,
  facebook: RiFacebookCircleLine,
  instagram: RiInstagramLine,
  twitter: RiTwitchLine,
  youtube: RiYoutubeLine,
  bar_chart: RiBarChart2Line,
  pie_chart: RiPieChartLine,
  email: RiMailSendLine,
  discount: RiDiscountPercentLine,
  delivery: RiTruckLine,
  payment: RiBankCardLine,
  secure: RiLockLine,
  refund: RiReplay10Line,
  arrow_right: RiArrowRightLine,
  arrow_left: RiArrowLeftLine,
  search: RiSearchLine,
  cart: RiShoppingCart2Line,
  success: RiCheckboxCircleFill,
  success_line: RiCheckboxCircleLine,
  cancel: RiCloseCircleFill,
  cancel_line: RiCloseCircleLine,
  error: RiCloseCircleFill,
  close: RiCloseLine,
  add: RiAddLine,
  add_circle: RiAddCircleLine,
  trash_can: RiDeleteBinLine,
  subtract: RiSubtractLine,
  edit: RiEdit2Line,
  breadcrumb_next: RiArrowRightDoubleLine,
  store: RiStore2Line,
  location: RiMapPin2Line,
  rupees: RiMoneyRupeeCircleLine,
  list_check: RiListCheck3,
  calender_check: RiCalendarCheckLine,
  history: RiHistoryLine,
  menu: RiMenu2Line,
  settings: RiSettingsLine,
  user: RiUserLine,
  logout: RiLogoutCircleRLine,
  upload: RiUpload2Line
}

export default icons